### ISSUE TITLE
onTurn doesn't check if context.activity.value is defined before accessing context.activity.value.commandId

### ISSUE THREAD

**Issue by greyseer256** [wictorwilen/botbuilder-teams-messagingextensions#6]
I am encountering an error [on line 117](https://github.com/wictorwilen/botbuilder-teams-messagingextensions/blob/master/src/index.ts#L117).
```
[onTurnError] unhandled error: TypeError: Cannot read property 'commandId' of undefined
```
In my situation `context.activity.value` is `undefined`. For background I'm using `adapter.continueConversation`, which seems to create an activity with `name: continueConversation` but no value.

If I change [line 116](https://github.com/wictorwilen/botbuilder-teams-messagingextensions/blob/master/src/index.ts#L116) to 
```js
if (this.commandId !== undefined && context.activity.value !== undefined) {
```
everything works fine. 

Happy to file a PR.

**Comment by wictorwilen** [comment]
Thanks for finding this. I'd love to see a PR (to the `preview` branch please) and I'll get it merged and published as soon as possible
