### ISSUE TITLE
botMessagePreview functionality does not work completely

### ISSUE THREAD

**Issue by kavins14** [wictorwilen/botbuilder-teams-messagingextensions#8]
I'm using the messaging extension middleware to create an action-based command which displays an adaptive card within the task module. The adaptive card has a submit action which triggers the `onSubmitAction` function.  From there I'm using the `botMessagePreview` type in the response. All this works fine but the issue arises when handling submit actions from the `Edit` and `Submit` buttons from the `botMessagePreview` task module. When the `Edit` submit action is triggered, `onSubmitAction` is run and I want to send the original task module back to the teams client. However for that to work the return value has to be of type `TaskModuleContinueResponse` but the function and the middleware does not handle that case.

I figured out that the issue is because of the `composeExtension` in the activity being sent on line 244: https://github.com/wictorwilen/botbuilder-teams-messagingextensions/blob/5cec69843eee5784944f6ecea4d3605df306a098/src/index.ts#L235-L248

A similar issue also shows up when the `Submit` action is triggered but I'm currently working around it by calling `sendActivity` from the `onSubmitAction` function itself.

Here's the [doc](https://docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/action-commands/respond-to-task-module-submit?tabs=dotnet#bot-response-with-adaptive-card) detailing the `botMessagePreview` functionality.

The `botMessagePreview` functionality is cruicial to the application I'm currently building and I would appreciate it if it can be resolved as soon as possible. Also, I can create a PR for this but before that I wanted to know your thoughts on this.

**Comment by wictorwilen** [comment]
Thanks for this. I'd love to improve/add the support for this. Feel free to create a PR and we'll look into how it works and how we can support a smooth upgrade for existing solutions.

Thanks
